### ISSUE TITLE
bulk database data example

### ISSUE THREAD

**Issue by roboto-cloud** [cezerin/docker-cezerin#1]
someone know how load data example and admin credential info into the container?

thanks in advance,

**Comment by restmount** [comment]
Tomorrow I will send you an example.

**Comment by roboto-cloud** [comment]
I'm playing around it.

docker exec -it [container name] bash
mongoimport --file default.json
https://github.com/cezerin/cezerin/wiki/installation#add-default-data-mongodb

mongoimport --file indexes.json
https://github.com/cezerin/cezerin/wiki/installation#add-indexes-mongodb

thanks in advance,

**Comment by roboto-cloud** [comment]
Hi @restmount, some new about how bulk database data example
or more important for me: how get admin access to manage the Client-side dashboard?

thanks in advance,

**Comment by restmount** [comment]
@roboto-cloud 
Please, follow this instruction: https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md
