### ISSUE TITLE
generate access tokens

### ISSUE THREAD

**Issue by roboto-cloud** [cezerin/docker-cezerin#2]
Hi, someone know the way to generate access tokens or admin access credentials? 
I use it and don't let me dive on Demo dashboard is an kind of read only access...

http://demosite.com/admin/login?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InB1YmxpY0BjZXplcmluLmNvbSIsInNjb3BlcyI6WyJyZWFkOnNldHRpbmdzIiwicmVhZDpwYXltZW50X21ldGhvZHMiLCJyZWFkOnNoaXBwaW5nX21ldGhvZHMiLCJyZWFkOnNpdGVtYXAiLCJyZWFkOnRoZW1lcyIsInJlYWQ6b3JkZXJfc3RhdHVzZXMiLCJyZWFkOnBhZ2VzIiwicmVhZDpjdXN0b21lcl9ncm91cHMiLCJyZWFkOmN1c3RvbWVycyIsInJlYWQ6b3JkZXJzIiwicmVhZDpwcm9kdWN0X2NhdGVnb3JpZXMiLCJyZWFkOnByb2R1Y3RzIiwiZGFzaGJvYXJkIl0sImp0aSI6IjU5MzkyZjRkMWMwYTQzMDEyMDE2YmEyNSIsImlhdCI6MTQ5NjkxOTg4NSwiZXhwIjoxNTEyNDcxODg1fQ._x3vJ9NoBL1zdNwFvTRFvAQv3HbwCeW53yt14hRm99U

and if I use mongo-express, that is all what I see:
![screenshot from 2017-11-02 18-24-16](https://user-images.githubusercontent.com/32390825/32340539-32f6fe38-bffb-11e7-9c5f-12f813e474f8.png)

thanks in advance,

**Comment by restmount** [comment]
@roboto-cloud 
insert to MongoDB this:

```js
db.tokens.insert({
  is_revoked: false,
  date_created: new Date(),
  expiration: 72,
  name: 'Owner',
  email: 'mail@domain.com',
  scopes: ['admin']  
});
```

Where **mail@domain.com** - your email. Dashboard will send to this email login link.
Also you need a mail server.
